
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-20T19:28:42-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "64b0e508124efa919649862f0483f9f7c2e90e71",
 "version": "0.0.8.dev20230227"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
