
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-27T16:11:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a5419ed81e95210d41561e35ff14db836fff09e3",
 "version": "0.8.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
