# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['meme_generator',
 'meme_generator.memes.5000choyen',
 'meme_generator.memes.addiction',
 'meme_generator.memes.alike',
 'meme_generator.memes.always',
 'meme_generator.memes.always_like',
 'meme_generator.memes.anti_kidnap',
 'meme_generator.memes.anya_suki',
 'meme_generator.memes.applaud',
 'meme_generator.memes.ascension',
 'meme_generator.memes.ask',
 'meme_generator.memes.back_to_work',
 'meme_generator.memes.bad_news',
 'meme_generator.memes.bite',
 'meme_generator.memes.blood_pressure',
 'meme_generator.memes.bocchi_draft',
 'meme_generator.memes.bronya_holdsign',
 'meme_generator.memes.call_110',
 'meme_generator.memes.capoo_rub',
 'meme_generator.memes.captain',
 'meme_generator.memes.charpic',
 'meme_generator.memes.chase_train',
 'meme_generator.memes.china_flag',
 'meme_generator.memes.confuse',
 'meme_generator.memes.coupon',
 'meme_generator.memes.cover_face',
 'meme_generator.memes.crawl',
 'meme_generator.memes.cyan',
 'meme_generator.memes.decent_kiss',
 'meme_generator.memes.dianzhongdian',
 'meme_generator.memes.dinosaur',
 'meme_generator.memes.distracted',
 'meme_generator.memes.divorce',
 'meme_generator.memes.dont_touch',
 'meme_generator.memes.douyin',
 'meme_generator.memes.eat',
 'meme_generator.memes.fanatic',
 'meme_generator.memes.fencing',
 'meme_generator.memes.find_chips',
 'meme_generator.memes.follow',
 'meme_generator.memes.funny_mirror',
 'meme_generator.memes.garbage',
 'meme_generator.memes.gif_subtitle',
 'meme_generator.memes.good_news',
 'meme_generator.memes.google',
 'meme_generator.memes.gun',
 'meme_generator.memes.hammer',
 'meme_generator.memes.high_EQ',
 'meme_generator.memes.hit_screen',
 'meme_generator.memes.hold_grudge',
 'meme_generator.memes.hold_tight',
 'meme_generator.memes.hug_leg',
 'meme_generator.memes.hutao_bite',
 'meme_generator.memes.imprison',
 'meme_generator.memes.incivilization',
 'meme_generator.memes.interview',
 'meme_generator.memes.jiji_king',
 'meme_generator.memes.jiujiu',
 'meme_generator.memes.kaleidoscope',
 'meme_generator.memes.karyl_point',
 'meme_generator.memes.keep_away',
 'meme_generator.memes.kick_ball',
 'meme_generator.memes.kirby_hammer',
 'meme_generator.memes.kiss',
 'meme_generator.memes.klee_eat',
 'meme_generator.memes.knock',
 'meme_generator.memes.learn',
 'meme_generator.memes.lim_x_0',
 'meme_generator.memes.listen_music',
 'meme_generator.memes.little_angel',
 'meme_generator.memes.loading',
 'meme_generator.memes.look_flat',
 'meme_generator.memes.look_this_icon',
 'meme_generator.memes.love_you',
 'meme_generator.memes.luxun_say',
 'meme_generator.memes.make_friend',
 'meme_generator.memes.marriage',
 'meme_generator.memes.meteor',
 'meme_generator.memes.murmur',
 'meme_generator.memes.my_friend',
 'meme_generator.memes.my_wife',
 'meme_generator.memes.name_generator',
 'meme_generator.memes.need',
 'meme_generator.memes.no_response',
 'meme_generator.memes.nokia',
 'meme_generator.memes.not_call_me',
 'meme_generator.memes.overtime',
 'meme_generator.memes.paint',
 'meme_generator.memes.painter',
 'meme_generator.memes.pat',
 'meme_generator.memes.perfect',
 'meme_generator.memes.petpet',
 'meme_generator.memes.play',
 'meme_generator.memes.play_game',
 'meme_generator.memes.police',
 'meme_generator.memes.pornhub',
 'meme_generator.memes.potato',
 'meme_generator.memes.pound',
 'meme_generator.memes.printing',
 'meme_generator.memes.prpr',
 'meme_generator.memes.psyduck',
 'meme_generator.memes.punch',
 'meme_generator.memes.raise_sign',
 'meme_generator.memes.read_book',
 'meme_generator.memes.repeat',
 'meme_generator.memes.rip',
 'meme_generator.memes.rip_angrily',
 'meme_generator.memes.rise_dead',
 'meme_generator.memes.roll',
 'meme_generator.memes.rub',
 'meme_generator.memes.run',
 'meme_generator.memes.safe_sense',
 'meme_generator.memes.scratch_head',
 'meme_generator.memes.scratchcard',
 'meme_generator.memes.scroll',
 'meme_generator.memes.shock',
 'meme_generator.memes.shutup',
 'meme_generator.memes.sit_still',
 'meme_generator.memes.slap',
 'meme_generator.memes.slogan',
 'meme_generator.memes.smash',
 'meme_generator.memes.suck',
 'meme_generator.memes.support',
 'meme_generator.memes.symmetric',
 'meme_generator.memes.tankuku_raisesign',
 'meme_generator.memes.teach',
 'meme_generator.memes.think_what',
 'meme_generator.memes.throw',
 'meme_generator.memes.throw_gif',
 'meme_generator.memes.thump',
 'meme_generator.memes.tightly',
 'meme_generator.memes.together',
 'meme_generator.memes.trance',
 'meme_generator.memes.turn',
 'meme_generator.memes.twist',
 'meme_generator.memes.universal',
 'meme_generator.memes.wakeup',
 'meme_generator.memes.wallpaper',
 'meme_generator.memes.walnut_pad',
 'meme_generator.memes.walnut_zoom',
 'meme_generator.memes.wave',
 'meme_generator.memes.why_at_me',
 'meme_generator.memes.windmill_turn',
 'meme_generator.memes.wish_fail',
 'meme_generator.memes.wooden_fish',
 'meme_generator.memes.worship',
 'meme_generator.memes.wujing',
 'meme_generator.memes.youtube']

package_data = \
{'': ['*']}

install_requires = \
['fastapi>=0.87.0,<1.0.0',
 'filetype>=1.2.0,<2.0.0',
 'httpx>=0.20.0,<1.0.0',
 'loguru>=0.6.0,<0.7.0',
 'pil-utils>=0.1.0,<0.2.0',
 'python-multipart>=0.0.5,<0.0.6',
 'toml>=0.10.2,<0.11.0',
 'tqdm>=4.60.0,<5.0.0',
 'uvicorn>0.17.0,<1.0.0']

entry_points = \
{'console_scripts': ['meme = meme_generator.cli:main']}

setup_kwargs = {
    'name': 'meme-generator',
    'version': '0.0.1a2',
    'description': 'Python package for making fun pictures',
    'long_description': '# meme_generator\n\n### TODO\n\n- [x] 加载表情\n- [x] 调用表情\n- [x] 构建 API\n- [x] cli 方式调用\n- [x] 配置项设置\n- [x] 迁移 petpet 和 memes 的表情\n- [ ] 图片打包方式（计划在 setup.py 中完成图片下载）\n',
    'author': 'meetwq',
    'author_email': 'meetwq@gmail.com',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'https://github.com/MeetWq/meme-generator',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.8,<4.0',
}


setup(**setup_kwargs)
