
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1835ba5fd62a48e2ae2df0c351a0e1f6e1979fbe",
 "version": "1.0.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
