# Generated by Django 3.2.5 on 2023-02-27 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeaccounting',
            old_name='debit_credit_flag',
            new_name='type',
        ),
    ]
