# coding: utf-8
# file generated by setuptools_scm + setup.py
# don't change, don't track in version control
git_hash = b'\xf0w\xb0x'
full_git_hash = 'f077b0784ca87e48bd83bcad15b3b776faf10e11'
git_branch = 'HEAD'
dirty = False
