
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-01-31T11:50:48+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "0e42f48100cce8837dc4005c72d53a4a46122804",
 "version": "1.3.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
