# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_processor/text_processor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#text_processor/text_processor.proto\x12\x14text_processor_proto\"\x17\n\x07Request\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07summary\x18\x01 \x01(\t2\xb9\x01\n\x17TextProcessorController\x12J\n\tSummarize\x12\x1d.text_processor_proto.Request\x1a\x1e.text_processor_proto.Response\x12R\n\x11SentimentAnalysis\x12\x1d.text_processor_proto.Request\x1a\x1e.text_processor_proto.Responseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_processor.text_processor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=61
  _REQUEST._serialized_end=84
  _RESPONSE._serialized_start=86
  _RESPONSE._serialized_end=113
  _TEXTPROCESSORCONTROLLER._serialized_start=116
  _TEXTPROCESSORCONTROLLER._serialized_end=301
# @@protoc_insertion_point(module_scope)
