# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kiwi.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nkiwi.proto\x12\x08\x65ndpoint\"$\n\rGetMsgRequest\x12\x13\n\x0bmsg_channel\x18\x01 \x01(\x03\"U\n\x0eGetMsgResponse\x12\x11\n\tmsg_level\x18\x01 \x01(\x03\x12\x10\n\x08msg_type\x18\x02 \x01(\x03\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x0b\n\x03msg\x18\x04 \x01(\t2N\n\x0bKiwiService\x12?\n\x06GetMsg\x12\x17.endpoint.GetMsgRequest\x1a\x18.endpoint.GetMsgResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kiwi_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETMSGREQUEST._serialized_start=24
  _GETMSGREQUEST._serialized_end=60
  _GETMSGRESPONSE._serialized_start=62
  _GETMSGRESPONSE._serialized_end=147
  _KIWISERVICE._serialized_start=149
  _KIWISERVICE._serialized_end=227
# @@protoc_insertion_point(module_scope)
