
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-24T12:31:51-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "8766ee90fa64d4d0378f08babb6043b6f9685e33",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
