
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-28T15:00:59-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "d2b361cff0bda3581af53a0fc6c75bd9667f4631",
 "version": "1.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
