# coding: utf-8

"""
    Datový konektor Domino pro eSMLOUVY

    Toto je datový konektor umožňující datovou výměnu mezi obchodní logikou aplikace eSMLOUVY a datovým serverem HCL Domino.  Ovládá se pomocí REST API   # noqa: E501

    OpenAPI spec version: 1.1.1
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import esmlouvy_connector
from esmlouvy_connector.models.container import Container  # noqa: E501
from esmlouvy_connector.rest import ApiException


class TestContainer(unittest.TestCase):
    """Container unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContainer(self):
        """Test Container"""
        # FIXME: construct object with mandatory attributes with example values
        # model = esmlouvy_connector.models.container.Container()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
