
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-28T10:08:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f9fb40eb85636bee01b86cca1f7c3e9a28380216",
 "version": "1.7.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
