from distutils.core import setup
setup(
  name = 'inputHelp',
  packages = ['inputHelp'],
  version = '1.0',
  license='MIT',
  description = 'Contains functions to validate input for command line programs',
  author = 'c20h12untitled',
  url = 'https://github.com/C20H12/inputHelpPackage',
  download_url = 'https://github.com/C20H12/inputHelpPackage/archive/refs/tags/1.0.tar.gz',
  keywords = ['input', 'command line'],
  install_requires=[],
  classifiers=[
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Environment :: Console'
  ],
)