import os

SV288_AGENT_DOMAIN = os.getenv('SV288_AGENT_DOMAIN', 'https://www.sfv288.com/')
SV288_CASINO_CATEGORIES = os.getenv('SV288_CASINO_CATEGORIES', 'HRB,SEXYBCRT,VENUS,FACHAI,JDB,JDBFISH,JILI,KINGMAKER,MIMI')
