
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-27T19:31:06-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "452ac945a0f6b558c30126e33d58cc78342ccb85",
 "version": "v1.0.0rc11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
