"""
    IoT Reports API

    IoT Reports API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: joe.savage@silabs.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import iotreports_client
from iotreports_client.model.report import Report
from iotreports_client.model.report_type import ReportType
globals()['Report'] = Report
globals()['ReportType'] = ReportType
from iotreports_client.model.inline_response2007 import InlineResponse2007


class TestInlineResponse2007(unittest.TestCase):
    """InlineResponse2007 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2007(self):
        """Test InlineResponse2007"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2007()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
