"""
    IoT Reports API

    IoT Reports API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: joe.savage@silabs.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import iotreports_client
from iotreports_client.api.report_api import ReportApi  # noqa: E501


class TestReportApi(unittest.TestCase):
    """ReportApi unit test stubs"""

    def setUp(self):
        self.api = ReportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_report(self):
        """Test case for create_report

        creates a report for an organization  # noqa: E501
        """
        pass

    def test_delete_report(self):
        """Test case for delete_report

        deletes a report  # noqa: E501
        """
        pass

    def test_get_report(self):
        """Test case for get_report

        gets a report  # noqa: E501
        """
        pass

    def test_get_report_and_type(self):
        """Test case for get_report_and_type

        gets a report and the corresponding reportType  # noqa: E501
        """
        pass

    def test_get_reports(self):
        """Test case for get_reports

        gets the reports for an organization  # noqa: E501
        """
        pass

    def test_get_reports_and_categories(self):
        """Test case for get_reports_and_categories

        gets all reports and categories for the specified organization  # noqa: E501
        """
        pass

    def test_update_report(self):
        """Test case for update_report

        updates a report  # noqa: E501
        """
        pass

    def test_update_report_stream(self):
        """Test case for update_report_stream

        updates a report stream  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
