"""
    IoT Reports API

    IoT Reports API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: joe.savage@silabs.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import iotreports_client
from iotreports_client.api.user_api import UserApi  # noqa: E501


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user_token(self):
        """Test case for create_user_token

        creates API token with specified name for a user  # noqa: E501
        """
        pass

    def test_delete_user_token(self):
        """Test case for delete_user_token

        deletes a user API token  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        gets user info corresponding to JWT token  # noqa: E501
        """
        pass

    def test_get_user_tokens(self):
        """Test case for get_user_tokens

        gets API tokens for a user  # noqa: E501
        """
        pass

    def test_login_user(self):
        """Test case for login_user

        user login  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
