# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions

from ...core.datetime_utils import serialize_datetime
from .document_response import DocumentResponse


class DocumentListResponse(pydantic.BaseModel):
    documents: typing.List[DocumentResponse]
    next_page: typing.Optional[int]
    total_pages: int

    class Partial(typing_extensions.TypedDict):
        documents: typing_extensions.NotRequired[typing.List[DocumentResponse]]
        next_page: typing_extensions.NotRequired[typing.Optional[int]]
        total_pages: typing_extensions.NotRequired[int]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        json_encoders = {dt.datetime: serialize_datetime}
