
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-01T22:18:57+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c892446ab4acfe2799e03a21da312116dc5e3f45",
 "version": "7.24.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
