VERSION_YEAR = 2023
VERSION_MONTH = int('02')
VERSION_DAY = int('28')
VERSION_HOUR = int('06')
VERSION_MINUTE = int('36')
MAJOR_VERSION = 1
MINOR_VERSION = 2
PATCH_VERSION = 202302280636
version_date = '2023/02/28 06:36'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
