
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-27T16:15:56-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f427c0dfe6d15f1bc607e813adec0eddf5ebeab",
 "version": "3.3.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
