
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-24T13:43:37+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ad0118350dee4fefaf9747dfa08acba0e606772",
 "version": "0.9.94"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
