
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-24T15:10:51+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c498cb07819e8f54dc761f5a37dc3aed2152505",
 "version": "0.3.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
