from pprint import pprint
import pytest
from time import sleep 

from pybmd import *
from pybmd.project_manager import ProjectManager
from pybmd.toolkits import *


@pytest.fixture()
def init_project_manager():
    LOCAL_RESOLVE=Bmd()
    LOCAL_FUSION=LOCAL_RESOLVE.fusion()
    project_manager=LOCAL_RESOLVE.get_project_manager()
    
    yield project_manager

def test_project(init_project_manager:ProjectManager):
    current_project=init_project_manager.get_current_project()
    assert current_project.get_name() == "80220401_Still_SDR"

from pybmd import timeline
print(timeline.TrackType)


# pprint(current_project.get_setting())


# print("current project name:",current_project.get_name())

# current_meida_storage=LOCAL_RESOLVE.get_media_stroage()
# file_list=current_meida_storage.get_file_list('/Users/wheheohu/Desktop/H2R_Files/TestFiles')
# current_meida_storage.add_item_list_to_meida_pool(file_list)



# folder_list=media_pool.get_current_folder().get_sub_folder_list()
# if len(folder_list)>0:
#     folder=folder_list[0]
#     media_list=folder.get_clip_list()
# else:
#     print("No folder found")

# pprint(current_project.set_current_render_mode(0))
# print(" clip number in folder", folder.get_name(), ":", len(media_list))
# pprint(media_list[0].get_clip_property())
# pprint(media_list[0].get_media_id())
# pprint(media_list[1].get_media_id())

##############################################################################################
#Project settings
# {'audioCaptureNumChannels': '2',
#  'audioOutputHasTimecode': '0',
#  'audioPlayoutNumChannels': '2',
#  'colorAcesGamutCompressType': 'None',
#  'colorAcesIDT': 'No Input Transform',
#  'colorAcesNodeLUTProcessingSpace': 'acesccAp1',
#  'colorAcesODT': 'No Output Transform',
#  'colorGalleryStillsLocation': '/Users/wheheohu/Movies/.gallery',
#  'colorGalleryStillsNamingCustomPattern': '%{Source Name}',
#  'colorGalleryStillsNamingEnabled': '1',
#  'colorGalleryStillsNamingPattern': 'customLabel',
#  'colorGalleryStillsNamingWithStillNumber': 'off',
#  'colorKeyframeDynamicsEndProfile': '1',
#  'colorKeyframeDynamicsStartProfile': '1',
#  'colorLuminanceMixerDefaultZero': '0',
#  'colorScienceMode': 'davinciYRGB',
#  'colorSpaceInput': 'Rec.709 Gamma 2.4',
#  'colorSpaceInputGamma': '',
#  'colorSpaceOutput': 'Same as Timeline',
#  'colorSpaceOutputGamma': 'Gamma 2.4',
#  'colorSpaceOutputGamutMapping': 'None',
#  'colorSpaceOutputGamutSaturationKnee': '0.9',
#  'colorSpaceOutputGamutSaturationMax': '1',
#  'colorSpaceOutputToneLuminanceMax': '100',
#  'colorSpaceOutputToneMapping': 'None',
#  'colorSpaceTimeline': 'Rec.709',
#  'colorSpaceTimelineGamma': '',
#  'colorUseBGRPixelOrderForDPX': '0',
#  'colorUseContrastSCurve': '1',
#  'colorUseLegacyLogGrades': '2',
#  'colorUseLocalVersionsAsDefault': '1',
#  'colorUseStereoConvergenceForEffects': '0',
#  'colorVersion10Name': '',
#  'colorVersion1Name': '',
#  'colorVersion2Name': '',
#  'colorVersion3Name': '',
#  'colorVersion4Name': '',
#  'colorVersion5Name': '',
#  'colorVersion6Name': '',
#  'colorVersion7Name': '',
#  'colorVersion8Name': '',
#  'colorVersion9Name': '',
#  'graphicsWhiteLevel': '100',
#  'hdr10PlusControlsOn': '0',
#  'hdrDolbyControlsOn': '0',
#  'hdrDolbyMasterDisplay': '4000-nit, P3, D65, ST.2084, Full',
#  'hdrDolbyVersion': '4.0',
#  'hdrMasteringLuminanceMax': '1000',
#  'hdrMasteringOn': '0',
#  'imageDeinterlaceQuality': 'normal',
#  'imageEnableFieldProcessing': '0',
#  'imageMotionEstimationMode': 'standardFaster',
#  'imageMotionEstimationRange': 'medium',
#  'imageResizeMode': 'sharper',
#  'imageResizingGamma': 'Timeline',
#  'imageRetimeInterpolation': 'nearest',
#  'inputDRT': 'None',
#  'inputDRTSatRolloffLimit': '10000',
#  'inputDRTSatRolloffStart': '100',
#  'isAutoColorManage': '0',
#  'limitAudioMeterAlignLevel': '0',
#  'limitAudioMeterDisplayMode': 'post_fader',
#  'limitAudioMeterHighLevel': '-5',
#  'limitAudioMeterLUFS': '-23',
#  'limitAudioMeterLoudnessScale': 'ebu_9_scale',
#  'limitAudioMeterLowLevel': '-10',
#  'limitBroadcastSafeLevels': '20_120',
#  'limitBroadcastSafeOn': '0',
#  'limitSubtitleCPL': '60',
#  'limitSubtitleCaptionDurationSec': '3',
#  'outputDRT': 'None',
#  'outputDRTSatRolloffLimit': '10000',
#  'outputDRTSatRolloffStart': '100',
#  'perfAutoRenderCacheAfterTime': '5',
#  'perfAutoRenderCacheComposite': '0',
#  'perfAutoRenderCacheEnable': '1',
#  'perfAutoRenderCacheFuEffect': '1',
#  'perfAutoRenderCacheTransition': '0',
#  'perfCacheClipsLocation': 'CacheClip',
#  'perfOptimisedCodec': 'apch',
#  'perfOptimisedMediaOn': '1',
#  'perfOptimizedResolutionRatio': 'auto',
#  'perfProxyMediaOn': '1',
#  'perfProxyResolutionRatio': 'original',
#  'perfRenderCacheCodec': 'apch',
#  'perfRenderCacheMode': 'none',
#  'rcmPresetMode': 'Custom',
#  'separateColorSpaceAndGamma': '0',
#  'superScale': 1,
#  'superScaleNoiseReduction': 'Medium',
#  'superScaleSharpness': 'Medium',
#  'timelineDropFrameTimecode': '0',
#  'timelineFrameRate': 25.0,
#  'timelineFrameRateMismatchBehavior': 'resolve',
#  'timelineInputResMismatchBehavior': 'scaleToFit',
#  'timelineInputResMismatchCustomPreset': 'None',
#  'timelineInputResMismatchUseCustomPreset': '0',
#  'timelineInterlaceProcessing': '0',
#  'timelineOutputPixelAspectRatio': 'square',
#  'timelineOutputResMatchTimelineRes': '1',
#  'timelineOutputResMismatchBehavior': 'scaleToFit',
#  'timelineOutputResMismatchCustomPreset': 'None',
#  'timelineOutputResMismatchUseCustomPreset': '0',
#  'timelineOutputResolutionHeight': '1080',
#  'timelineOutputResolutionWidth': '1080',
#  'timelinePixelAspectRatio': 'square',
#  'timelinePlaybackFrameRate': '25',
#  'timelineResolutionHeight': '1080',
#  'timelineResolutionWidth': '1080',
#  'timelineSaveThumbsInProject': '0',
#  'timelineWorkingLuminance': '1000',
#  'timelineWorkingLuminanceMode': 'HDR 1000',
#  'useCATransform': '1',
#  'useColorSpaceAwareGradingTools': '0',
#  'useInverseDRT': '0',
#  'videoCaptureCodec': 'apch',
#  'videoCaptureFormat': 'mov',
#  'videoCaptureIngestHandles': '0',
#  'videoCaptureLocation': '/Users/wheheohu/Movies/Capture',
#  'videoCaptureMode': 'video_audio',
#  'videoDataLevels': 'Video',
#  'videoDataLevelsRetainSubblockAndSuperWhiteData': '0',
#  'videoDeckAdd32Pulldown': '0',
#  'videoDeckBitDepth': '10',
#  'videoDeckFormat': 'HD 1080PsF 24',
#  'videoDeckNonAutoEditFrames': '0',
#  'videoDeckOutputSyncSource': 'auto',
#  'videoDeckPrerollSec': '5',
#  'videoDeckSDIConfiguration': 'none',
#  'videoDeckUse444SDI': '0',
#  'videoDeckUseAudoEdit': '1',
#  'videoDeckUseStereoSDI': '0',
#  'videoMonitorBitDepth': '10',
#  'videoMonitorFormat': 'HD 1080PsF 25',
#  'videoMonitorMatrixOverrideFor422SDI': 'Rec.601',
#  'videoMonitorSDIConfiguration': 'dual_link',
#  'videoMonitorScaling': 'bilinear',
#  'videoMonitorUse444SDI': '0',
#  'videoMonitorUseHDROverHDMI': '0',
#  'videoMonitorUseLevelA': '0',
#  'videoMonitorUseMatrixOverrideFor422SDI': '0',
#  'videoMonitorUseStereoSDI': '0',
#  'videoPlayoutAudioFramesOffset': '0',
#  'videoPlayoutBatchHeadDuration': '8',
#  'videoPlayoutBatchTailDuration': '8',
#  'videoPlayoutLTCFramesOffset': '0',
#  'videoPlayoutMode': 'video_audio',
#  'videoPlayoutShowLTC': '0',
#  'videoPlayoutShowSourceTimecode': '0'}

##############################################################################################
# Timeline settings

# 'audioCaptureNumChannels': '2',
#  'audioOutputHasTimecode': '0',
#  'audioPlayoutNumChannels': '2',
#  'colorAcesGamutCompressType': 'None',
#  'colorAcesIDT': 'No Input Transform',
#  'colorAcesNodeLUTProcessingSpace': 'acesccAp1',
#  'colorAcesODT': 'No Output Transform',
#  'colorGalleryStillsLocation': '/Users/wheheohu/Movies/.gallery',
#  'colorGalleryStillsNamingCustomPattern': '%{Source Name}',
#  'colorGalleryStillsNamingEnabled': '1',
#  'colorGalleryStillsNamingPattern': 'customLabel',
#  'colorGalleryStillsNamingWithStillNumber': 'off',
#  'colorKeyframeDynamicsEndProfile': '1',
#  'colorKeyframeDynamicsStartProfile': '1',
#  'colorLuminanceMixerDefaultZero': '0',
#  'colorScienceMode': 'davinciYRGBColorManagedv2',
#  'colorSpaceInput': 'ARRI Alexa V3',
#  'colorSpaceInputGamma': '',
#  'colorSpaceOutput': 'Rec.709 Gamma 2.4',
#  'colorSpaceOutputGamma': 'Gamma 2.4',
#  'colorSpaceOutputGamutMapping': 'None',
#  'colorSpaceOutputGamutSaturationKnee': '0.9',
#  'colorSpaceOutputGamutSaturationMax': '1',
#  'colorSpaceOutputToneLuminanceMax': '100',
#  'colorSpaceOutputToneMapping': 'None',
#  'colorSpaceTimeline': 'DaVinci WG',
#  'colorSpaceTimelineGamma': '',
#  'colorUseBGRPixelOrderForDPX': '0',
#  'colorUseContrastSCurve': '1',
#  'colorUseLegacyLogGrades': '2',
#  'colorUseLocalVersionsAsDefault': '1',
#  'colorUseStereoConvergenceForEffects': '0',
#  'colorVersion10Name': '',
#  'colorVersion1Name': '',
#  'colorVersion2Name': '',
#  'colorVersion3Name': '',
#  'colorVersion4Name': '',
#  'colorVersion5Name': '',
#  'colorVersion6Name': '',
#  'colorVersion7Name': '',
#  'colorVersion8Name': '',
#  'colorVersion9Name': '',
#  'graphicsWhiteLevel': '100',
#  'hdr10PlusControlsOn': '0',
#  'hdrDolbyControlsOn': '0',
#  'hdrDolbyMasterDisplay': '4000-nit, P3, D65, ST.2084, Full',
#  'hdrDolbyVersion': '4.0',
#  'hdrMasteringLuminanceMax': '1000',
#  'hdrMasteringOn': '0',
#  'imageDeinterlaceQuality': 'normal',
#  'imageEnableFieldProcessing': '0',
#  'imageMotionEstimationMode': 'standardFaster',
#  'imageMotionEstimationRange': 'medium',
#  'imageResizeMode': 'sharper',
#  'imageResizingGamma': 'Gamma',
#  'imageRetimeInterpolation': 'nearest',
#  'inputDRT': 'DaVinci',
#  'inputDRTSatRolloffLimit': '10000',
#  'inputDRTSatRolloffStart': '100',
#  'isAutoColorManage': '0',
#  'limitAudioMeterAlignLevel': '0',
#  'limitAudioMeterDisplayMode': 'post_fader',
#  'limitAudioMeterHighLevel': '-5',
#  'limitAudioMeterLUFS': '-23',
#  'limitAudioMeterLoudnessScale': 'ebu_9_scale',
#  'limitAudioMeterLowLevel': '-10',
#  'limitBroadcastSafeLevels': '20_120',
#  'limitBroadcastSafeOn': '0',
#  'limitSubtitleCPL': '60',
#  'limitSubtitleCaptionDurationSec': '3',
#  'outputDRT': 'DaVinci',
#  'outputDRTSatRolloffLimit': '10000',
#  'outputDRTSatRolloffStart': '100',
#  'perfAutoRenderCacheAfterTime': '5',
#  'perfAutoRenderCacheComposite': '0',
#  'perfAutoRenderCacheEnable': '1',
#  'perfAutoRenderCacheFuEffect': '1',
#  'perfAutoRenderCacheTransition': '0',
#  'perfCacheClipsLocation': 'CacheClip',
#  'perfOptimisedCodec': 'apch',
#  'perfOptimisedMediaOn': '1',
#  'perfOptimizedResolutionRatio': 'auto',
#  'perfProxyMediaOn': '1',
#  'perfProxyResolutionRatio': 'original',
#  'perfRenderCacheCodec': 'apch',
#  'perfRenderCacheMode': 'none',
#  'rcmPresetMode': 'Custom',
#  'separateColorSpaceAndGamma': '0',
#  'superScale': 1,
#  'superScaleNoiseReduction': 'Medium',
#  'superScaleSharpness': 'Medium',
#  'timelineDropFrameTimecode': '0',
#  'timelineFrameRate': 25.0,
#  'timelineFrameRateMismatchBehavior': 'resolve',
#  'timelineInputResMismatchBehavior': 'scaleToFit',
#  'timelineInputResMismatchCustomPreset': 'None',
#  'timelineInputResMismatchUseCustomPreset': '0',
#  'timelineInterlaceProcessing': '0',
#  'timelineOutputPixelAspectRatio': 'square',
#  'timelineOutputResMatchTimelineRes': '1',
#  'timelineOutputResMismatchBehavior': 'scaleToFit',
#  'timelineOutputResMismatchCustomPreset': 'None',
#  'timelineOutputResMismatchUseCustomPreset': '0',
#  'timelineOutputResolutionHeight': '1080',
#  'timelineOutputResolutionWidth': '1920',
#  'timelinePixelAspectRatio': 'square',
#  'timelinePlaybackFrameRate': '25',
#  'timelineResolutionHeight': '1080',
#  'timelineResolutionWidth': '1920',
#  'timelineSaveThumbsInProject': '0',
#  'timelineWorkingLuminance': '1000',
#  'timelineWorkingLuminanceMode': 'HDR 1000',
#  'useCATransform': '1',
#  'useColorSpaceAwareGradingTools': '1',
#  'useInverseDRT': '1',
#  'videoCaptureCodec': 'apch',
#  'videoCaptureFormat': 'mov',
#  'videoCaptureIngestHandles': '0',
#  'videoCaptureLocation': '/Users/wheheohu/Movies/Capture',
#  'videoCaptureMode': 'video_audio',
#  'videoDataLevels': 'Video',
#  'videoDataLevelsRetainSubblockAndSuperWhiteData': '0',
#  'videoDeckAdd32Pulldown': '0',
#  'videoDeckBitDepth': '10',
#  'videoDeckFormat': 'HD 1080PsF 24',
#  'videoDeckNonAutoEditFrames': '0',
#  'videoDeckOutputSyncSource': 'auto',
#  'videoDeckPrerollSec': '5',
#  'videoDeckSDIConfiguration': 'none',
#  'videoDeckUse444SDI': '0',
#  'videoDeckUseAudoEdit': '1',
#  'videoDeckUseStereoSDI': '0',
#  'videoMonitorBitDepth': '10',
#  'videoMonitorFormat': 'HD 1080PsF 25',
#  'videoMonitorMatrixOverrideFor422SDI': 'Rec.601',
#  'videoMonitorSDIConfiguration': 'dual_link',
#  'videoMonitorScaling': 'bilinear',
#  'videoMonitorUse444SDI': '0',
#  'videoMonitorUseHDROverHDMI': '0',
#  'videoMonitorUseLevelA': '0',
#  'videoMonitorUseMatrixOverrideFor422SDI': '0',
#  'videoMonitorUseStereoSDI': '0',
#  'videoPlayoutAudioFramesOffset': '0',
#  'videoPlayoutBatchHeadDuration': '8',
#  'videoPlayoutBatchTailDuration': '8',
#  'videoPlayoutLTCFramesOffset': '0',
#  'videoPlayoutMode': 'video_audio',
#  'videoPlayoutShowLTC': '0',
#  'videoPlayoutShowSourceTimecode': '0'

##############################################################################################
# clip_property for a video clip:

# 'Alpha mode': 'None',
# 'Angle': '',
# 'Audio Bit Depth': '32',
# 'Audio Ch': '2',
# 'Audio Codec': 'AAC',
# 'Audio Offset': '',
# 'Bit Depth': '8',
# 'Camera #': '',
# 'Clip Color': '',
# 'Clip Name': 'Watchtower of China.mp4',
# 'Comments': '',
# 'Data Level': 'Auto',
# 'Date Added': 'Mon Jul 25 2022 00:59:45',
# 'Date Created': 'Tue Jun 21 2022 08:42:53',
# 'Date Modified': 'Tue Jun 21 08:43:21 2022',
# 'Description': '',
# 'Drop frame': '0',
# 'Duration': '00:04:05:11',
# 'Enable Deinterlacing': '0',
# 'End': '6135',
# 'End TC': '00:04:05:11',
# 'FPS': 25.0,
# 'Field Dominance': 'Auto',
# 'File Name': 'Watchtower of China.mp4',
# 'File Path': '/Users/wheheohu/Desktop/Film_Ana/Watchtower of China/Watchtower '
#              'of China.mp4',
# 'Flags': '',
# 'Format': 'QuickTime',
# 'Frames': '6136',
# 'Good Take': '',
# 'H-FLIP': 'Off',
# 'IDT': '',
# 'In': '',
# 'Input Color Space': 'Rec.709-A',
# 'Input LUT': '',
# 'Input Sizing Preset': 'None',
# 'Keyword': '',
# 'Noise Reduction': '',
# 'Offline Reference': '',
# 'Out': '',
# 'PAR': 'Square',
# 'Proxy': 'None',
# 'Proxy Media Path': '',
# 'Reel Name': '',
# 'Resolution': '3840x2160',
# 'Roll/Card': '',
# 'S3D Sync': '',
# 'Sample Rate': '44100',
# 'Scene': '',
# 'Sharpness': '',
# 'Shot': '',
# 'Slate TC': '00:00:00:00',
# 'Start': '0',
# 'Start KeyKode': '',
# 'Start TC': '00:00:00:00',
# 'Super Scale': 1,
# 'Synced Audio': '',
# 'Take': '',
# 'Type': 'Video + Audio',
# 'Usage': '2',
# 'V-FLIP': 'Off',
# 'Video Codec': 'H.264 High L5.1'

 