
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-28T14:13:46-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "a5118bc15e0138d279c240df02365effd60bff9f",
 "version": "7.4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
