
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-25T11:22:21+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "26a158b6fd797bdded9e55c3becb36c9064c88ca",
 "version": "1.0.0a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
