VERSION_YEAR = 2023
VERSION_MONTH = int('02')
VERSION_DAY = int('28')
VERSION_HOUR = int('18')
VERSION_MINUTE = int('38')
MAJOR_VERSION = 1
MINOR_VERSION = 2
PATCH_VERSION = 202302281838
version_date = '2023/02/28 18:38'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
