# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['dfk_contracts', 'dfk_contracts.contracts']

package_data = \
{'': ['*']}

install_requires = \
['web3>=5.31.3,<6.0.0']

setup_kwargs = {
    'name': 'dfk-contracts',
    'version': '0.1.5',
    'description': 'Autogenerated Python wrapper for Defi Kingdoms Web3 contracts',
    'long_description': 'None',
    'author': 'Athiriyya',
    'author_email': 'athiriyya@gmail.com',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'None',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.10,<4.0',
}


setup(**setup_kwargs)
