#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pyluach']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

extras_require = \
{'doc': ['sphinx ~= 6.1.3', 'sphinx_rtd_theme ~= 1.2.0'],
 'test': ['pytest', 'pytest-cov', 'flake8', 'beautifulsoup4']}

setup(name='pyluach',
      version='2.2.0',
      description='A Python package for dealing with Hebrew (Jewish) calendar dates.',
      author=None,
      author_email='MS List <simlist@gmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
