# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import matcher_pb2 as matcher__pb2
import profile_pb2 as profile__pb2


class RecommendationStub(object):
    """Employer messages
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEmployeeRecommendation = channel.unary_unary(
                '/Recommendation/GetEmployeeRecommendation',
                request_serializer=profile__pb2.ProfileKey.SerializeToString,
                response_deserializer=profile__pb2.PositionKey.FromString,
                )
        self.SendEmployeeSwipeAction = channel.unary_unary(
                '/Recommendation/SendEmployeeSwipeAction',
                request_serializer=matcher__pb2.EmployeeSwipeAction.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetEmployeeMatches = channel.unary_stream(
                '/Recommendation/GetEmployeeMatches',
                request_serializer=matcher__pb2.GetEmployeeMatchesRequest.SerializeToString,
                response_deserializer=matcher__pb2.EmployeeMatch.FromString,
                )
        self.GetPositionRecommendation = channel.unary_unary(
                '/Recommendation/GetPositionRecommendation',
                request_serializer=profile__pb2.PositionKey.SerializeToString,
                response_deserializer=profile__pb2.ProfileKey.FromString,
                )
        self.SendPositionSwipeAction = channel.unary_unary(
                '/Recommendation/SendPositionSwipeAction',
                request_serializer=matcher__pb2.PositionSwipeAction.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetPositionMatches = channel.unary_stream(
                '/Recommendation/GetPositionMatches',
                request_serializer=matcher__pb2.GetPositionMatchesRequest.SerializeToString,
                response_deserializer=matcher__pb2.PositionMatch.FromString,
                )


class RecommendationServicer(object):
    """Employer messages
    """

    def GetEmployeeRecommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendEmployeeSwipeAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmployeeMatches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositionRecommendation(self, request, context):
        """Employee messages

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPositionSwipeAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositionMatches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEmployeeRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmployeeRecommendation,
                    request_deserializer=profile__pb2.ProfileKey.FromString,
                    response_serializer=profile__pb2.PositionKey.SerializeToString,
            ),
            'SendEmployeeSwipeAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEmployeeSwipeAction,
                    request_deserializer=matcher__pb2.EmployeeSwipeAction.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetEmployeeMatches': grpc.unary_stream_rpc_method_handler(
                    servicer.GetEmployeeMatches,
                    request_deserializer=matcher__pb2.GetEmployeeMatchesRequest.FromString,
                    response_serializer=matcher__pb2.EmployeeMatch.SerializeToString,
            ),
            'GetPositionRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositionRecommendation,
                    request_deserializer=profile__pb2.PositionKey.FromString,
                    response_serializer=profile__pb2.ProfileKey.SerializeToString,
            ),
            'SendPositionSwipeAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPositionSwipeAction,
                    request_deserializer=matcher__pb2.PositionSwipeAction.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetPositionMatches': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPositionMatches,
                    request_deserializer=matcher__pb2.GetPositionMatchesRequest.FromString,
                    response_serializer=matcher__pb2.PositionMatch.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Recommendation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Recommendation(object):
    """Employer messages
    """

    @staticmethod
    def GetEmployeeRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendation/GetEmployeeRecommendation',
            profile__pb2.ProfileKey.SerializeToString,
            profile__pb2.PositionKey.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendEmployeeSwipeAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendation/SendEmployeeSwipeAction',
            matcher__pb2.EmployeeSwipeAction.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEmployeeMatches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Recommendation/GetEmployeeMatches',
            matcher__pb2.GetEmployeeMatchesRequest.SerializeToString,
            matcher__pb2.EmployeeMatch.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPositionRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendation/GetPositionRecommendation',
            profile__pb2.PositionKey.SerializeToString,
            profile__pb2.ProfileKey.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendPositionSwipeAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Recommendation/SendPositionSwipeAction',
            matcher__pb2.PositionSwipeAction.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPositionMatches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Recommendation/GetPositionMatches',
            matcher__pb2.GetPositionMatchesRequest.SerializeToString,
            matcher__pb2.PositionMatch.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
