from religionnlp.buddhism.buddhism import *
from religionnlp.buddhism.eight_fold_path import *
from religionnlp.buddhism.four_noble_truths import *
from religionnlp.buddhism.nirvana import *
from religionnlp.buddhism.precepts import *
from religionnlp.buddhism.samadhi import *
from religionnlp.buddhism.xian_mi_jian_xiu import *
from religionnlp.buddhism.yuan import *
from religionnlp.buddhism.prajna import *
from religionnlp.buddhism.dhyana import *
from religionnlp.buddhism.transference_of_merit import *
from religionnlp.buddhism.abysmal_hell import *
