
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-28T13:30:06+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5e4b75e3e804d20763429e1a17d92ed769c4dd02",
 "version": "1.13.182"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
