
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-27T05:38:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fa4817deb8058b4f745f10017ca67c09819fe46a",
 "version": "1.18.2.post0.dev138"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
