# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from server.v1 import task_pb2 as server_dot_v1_dot_task__pb2


class TaskServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/server.v1.TaskService/CreateTask',
                request_serializer=server_dot_v1_dot_task__pb2.CreateTaskInput.SerializeToString,
                response_deserializer=server_dot_v1_dot_task__pb2.Task.FromString,
                )
        self.ListTask = channel.unary_unary(
                '/server.v1.TaskService/ListTask',
                request_serializer=server_dot_v1_dot_task__pb2.ListTaskInput.SerializeToString,
                response_deserializer=server_dot_v1_dot_task__pb2.ListTaskOutput.FromString,
                )
        self.GetNextTask = channel.unary_unary(
                '/server.v1.TaskService/GetNextTask',
                request_serializer=server_dot_v1_dot_task__pb2.GetNextTaskInput.SerializeToString,
                response_deserializer=server_dot_v1_dot_task__pb2.GetNextTaskOutput.FromString,
                )
        self.UpdateTask = channel.unary_unary(
                '/server.v1.TaskService/UpdateTask',
                request_serializer=server_dot_v1_dot_task__pb2.UpdateTaskInput.SerializeToString,
                response_deserializer=server_dot_v1_dot_task__pb2.Task.FromString,
                )
        self.GetTask = channel.unary_unary(
                '/server.v1.TaskService/GetTask',
                request_serializer=server_dot_v1_dot_task__pb2.GetTaskInput.SerializeToString,
                response_deserializer=server_dot_v1_dot_task__pb2.Task.FromString,
                )


class TaskServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=server_dot_v1_dot_task__pb2.CreateTaskInput.FromString,
                    response_serializer=server_dot_v1_dot_task__pb2.Task.SerializeToString,
            ),
            'ListTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTask,
                    request_deserializer=server_dot_v1_dot_task__pb2.ListTaskInput.FromString,
                    response_serializer=server_dot_v1_dot_task__pb2.ListTaskOutput.SerializeToString,
            ),
            'GetNextTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextTask,
                    request_deserializer=server_dot_v1_dot_task__pb2.GetNextTaskInput.FromString,
                    response_serializer=server_dot_v1_dot_task__pb2.GetNextTaskOutput.SerializeToString,
            ),
            'UpdateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTask,
                    request_deserializer=server_dot_v1_dot_task__pb2.UpdateTaskInput.FromString,
                    response_serializer=server_dot_v1_dot_task__pb2.Task.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=server_dot_v1_dot_task__pb2.GetTaskInput.FromString,
                    response_serializer=server_dot_v1_dot_task__pb2.Task.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server.v1.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.v1.TaskService/CreateTask',
            server_dot_v1_dot_task__pb2.CreateTaskInput.SerializeToString,
            server_dot_v1_dot_task__pb2.Task.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.v1.TaskService/ListTask',
            server_dot_v1_dot_task__pb2.ListTaskInput.SerializeToString,
            server_dot_v1_dot_task__pb2.ListTaskOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNextTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.v1.TaskService/GetNextTask',
            server_dot_v1_dot_task__pb2.GetNextTaskInput.SerializeToString,
            server_dot_v1_dot_task__pb2.GetNextTaskOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.v1.TaskService/UpdateTask',
            server_dot_v1_dot_task__pb2.UpdateTaskInput.SerializeToString,
            server_dot_v1_dot_task__pb2.Task.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/server.v1.TaskService/GetTask',
            server_dot_v1_dot_task__pb2.GetTaskInput.SerializeToString,
            server_dot_v1_dot_task__pb2.Task.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
