
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-26T12:13:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf343483ff6914bdd9191bd9cdd495ed166be68e",
 "version": "1.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
