# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ydb/core/yq/libs/config/protos/audit.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*ydb/core/yq/libs/config/protos/audit.proto\x12\x0bNYq.NConfig\"\x89\x01\n\x0cTAuditConfig\x12\x0f\n\x07\x45nabled\x18\x01 \x01(\x08\x12\x35\n\x08UAConfig\x18\x02 \x01(\x0b\x32#.NYq.NConfig.TAuditConfig.TUAConfig\x1a\x31\n\tTUAConfig\x12\x0b\n\x03Uri\x18\x01 \x01(\t\x12\x17\n\x0fSharedSecretKey\x18\x02 \x01(\tB\x1b\n\x16ru.yandex.kikimr.proto\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ydb.core.yq.libs.config.protos.audit_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026ru.yandex.kikimr.proto\370\001\001'
  _TAUDITCONFIG._serialized_start=60
  _TAUDITCONFIG._serialized_end=197
  _TAUDITCONFIG_TUACONFIG._serialized_start=148
  _TAUDITCONFIG_TUACONFIG._serialized_end=197
# @@protoc_insertion_point(module_scope)
