# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ydb/core/yq/libs/config/protos/nodes_manager.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2ydb/core/yq/libs/config/protos/nodes_manager.proto\x12\x0bNYq.NConfig\"m\n\x13TNodesManagerConfig\x12\x0f\n\x07\x45nabled\x18\x01 \x01(\x08\x12\x0c\n\x04Port\x18\x02 \x01(\r\x12\x0c\n\x04Host\x18\x03 \x01(\t\x12\x12\n\nDataCenter\x18\x04 \x01(\t\x12\x15\n\rUseDataCenter\x18\x05 \x01(\x08\x42\x1b\n\x16ru.yandex.kikimr.proto\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ydb.core.yq.libs.config.protos.nodes_manager_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026ru.yandex.kikimr.proto\370\001\001'
  _TNODESMANAGERCONFIG._serialized_start=67
  _TNODESMANAGERCONFIG._serialized_end=176
# @@protoc_insertion_point(module_scope)
