"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SpotifyFailureReason:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SpotifyFailureReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SpotifyFailureReason.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NONE: _SpotifyFailureReason.ValueType  # 0
    NOT_FOUND: _SpotifyFailureReason.ValueType  # 1
    API_REQUEST_REJECTED: _SpotifyFailureReason.ValueType  # 2
    TRANSPORT_FAILURE: _SpotifyFailureReason.ValueType  # 3

class SpotifyFailureReason(_SpotifyFailureReason, metaclass=_SpotifyFailureReasonEnumTypeWrapper): ...

NONE: SpotifyFailureReason.ValueType  # 0
NOT_FOUND: SpotifyFailureReason.ValueType  # 1
API_REQUEST_REJECTED: SpotifyFailureReason.ValueType  # 2
TRANSPORT_FAILURE: SpotifyFailureReason.ValueType  # 3
global___SpotifyFailureReason = SpotifyFailureReason

@typing_extensions.final
class SpotifySearchRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUERY_FIELD_NUMBER: builtins.int
    LIMIT_COUNT_FIELD_NUMBER: builtins.int
    query: builtins.str
    limit_count: builtins.int
    def __init__(
        self,
        *,
        query: builtins.str = ...,
        limit_count: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["limit_count", b"limit_count", "query", b"query"]) -> None: ...

global___SpotifySearchRequest = SpotifySearchRequest

@typing_extensions.final
class SpotifySearchedSong(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    AUTHOR_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    LENGTH_SECONDS_FIELD_NUMBER: builtins.int
    id: builtins.str
    author: builtins.str
    name: builtins.str
    length_seconds: builtins.float
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        author: builtins.str = ...,
        name: builtins.str = ...,
        length_seconds: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["author", b"author", "id", b"id", "length_seconds", b"length_seconds", "name", b"name"]) -> None: ...

global___SpotifySearchedSong = SpotifySearchedSong

@typing_extensions.final
class SpotifySearchResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FAILURE_REASON_FIELD_NUMBER: builtins.int
    SONGS_FIELD_NUMBER: builtins.int
    failure_reason: global___SpotifyFailureReason.ValueType
    @property
    def songs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SpotifySearchedSong]: ...
    def __init__(
        self,
        *,
        failure_reason: global___SpotifyFailureReason.ValueType = ...,
        songs: collections.abc.Iterable[global___SpotifySearchedSong] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["failure_reason", b"failure_reason", "songs", b"songs"]) -> None: ...

global___SpotifySearchResult = SpotifySearchResult

@typing_extensions.final
class SpotifyAnalysisRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id"]) -> None: ...

global___SpotifyAnalysisRequest = SpotifyAnalysisRequest

@typing_extensions.final
class SpotifyAnalysisResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FAILURE_REASON_FIELD_NUMBER: builtins.int
    ANALYSIS_JSON_FIELD_NUMBER: builtins.int
    failure_reason: global___SpotifyFailureReason.ValueType
    analysis_json: builtins.str
    def __init__(
        self,
        *,
        failure_reason: global___SpotifyFailureReason.ValueType = ...,
        analysis_json: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["analysis_json", b"analysis_json", "failure_reason", b"failure_reason"]) -> None: ...

global___SpotifyAnalysisResult = SpotifyAnalysisResult
