nucl_to_small_aa = dict(
            GCT="A",
            GCC="A",
            GCA="A",
            GCG="A",
            TTA="L",
            TTG="L",
            CTT="L",
            CTC="L",
            CTA="L",
            CTG="L",
            CGT="R",
            CGC="R",
            CGA="R",
            CGG="R",
            AGA="R",
            AGG="R",
            AAA="K",
            AAG="K",
            AAT="N",
            AAC="N",
            ATG="M",
            GAT="D",
            GAC="D",
            TTT="F",
            TTC="F",
            TGT="C",
            TGC="C",
            CCT="P",
            CCC="P",
            CCA="P",
            CCG="P",
            CAA="Q",
            CAG="Q",
            TCT="S",
            TCC="S",
            TCA="S",
            TCG="S",
            AGT="S",
            AGC="S",
            GAA="E",
            GAG="E",
            ACT="T",
            ACC="T",
            ACA="T",
            ACG="T",
            GGT="G",
            GGC="G",
            GGA="G",
            GGG="G",
            TGG="W",
            CAT="H",
            CAC="H",
            TAT="Y",
            TAC="Y",
            ATT="I",
            ATC="I",
            ATA="I",
            GTT="V",
            GTC="V",
            GTA="V",
            GTG="V",
            TAA="*",
            TGA="*",
            TAG="*",
        )

small_aa_to_long_aa = {
            "A": "Ala",
            "L": "Leu",
            "R": "Arg",
            "K": "Lys",
            "N": "Asn",
            "M": "Met",
            "D": "Asp",
            "F": "Phe",
            "C": "Cys",
            "P": "Pro",
            "Q": "Gln",
            "S": "Ser",
            "E": "Glu",
            "T": "Thr",
            "G": "Gly",
            "W": "Trp",
            "H": "His",
            "Y": "Tyr",
            "I": "Ile",
            "V": "Val",
            "*": "Ter",
        }

long_aa_to_small_aa = {
    "Ala": "A",
    "Leu": "L",
    "Arg": "R",
    "Lys": "K",
    "Asn": "N",
    "Met": "M",
    "Asp": "D",
    "Phe": "F",
    "Cys": "C",
    "Pro": "P",
    "Gln": "Q",
    "Ser": "S",
    "Glu": "E",
    "Thr": "T",
    "Gly": "G",
    "Trp": "W",
    "His": "H",
    "Tyr": "Y",
    "Ile": "I",
    "Val": "V",
    "Ter": "*",
}