
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.0.0'
version_full = '04e774d20508200e2ca5ef1d429a781709476484'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

