# !/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# Copyright (c) 2023 Baidu.com, Inc. All Rights Reserved

WORKSPACE_ID = 'WORKSPACE_ID'
MODEL_STORE_NAME = 'MODEL_STORE_NAME'
MODEL_NAME = 'MODEL_NAME'
MODEL_VERSION = 'MODEL_VERSION'

TIME_DIRECTORY_FORMAT = '%Y-%m-%d/%H'

CAPTURE_LOG_DIR = 'CAPTURE_LOG_DIR'
CAPTURE_BLOB_DIR = 'CAPTURE_BLOB_DIR'

ENABLE_CAPTURE_INPUT = 'ENABLE_CAPTURE_INPUT'
ENABLE_CAPTURE_PREDICTION = 'ENABLE_CAPTURE_PREDICTION'
ENABLE_CAPTURE_GROUND_TRUTH = 'ENABLE_CAPTURE_GROUND_TRUTH'

DEFAULT_CAPTURE_LOG_DIR = '/data/log'
DEFAULT_CAPTURE_BLOB_DIR = '/data/blob'

DEFAULT_CAPTURE_INPUT_DESIGNATION = 'inputs'
DEFAULT_CAPTURE_PREDICTION_DESIGNATION = 'predictions'
DEFAULT_CAPTURE_LABEL_DESIGNATION = 'labels'
