# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tag.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tag.proto',
  package='calixa.domain.tag',
  syntax='proto3',
  serialized_options=b'\n\024io.calixa.domain.tagH\001P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ttag.proto\x12\x11\x63\x61lixa.domain.tag\x1a\x0c\x63ommon.proto\"]\n\x03Tag\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x35\n\x0b\x65ntity_type\x18\x02 \x01(\x0e\x32 .calixa.domain.common.EntityType\x12\x11\n\thex_color\x18\x03 \x01(\tB\x1a\n\x14io.calixa.domain.tagH\x01P\x01\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_TAG = _descriptor.Descriptor(
  name='Tag',
  full_name='calixa.domain.tag.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='calixa.domain.tag.Tag.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entity_type', full_name='calixa.domain.tag.Tag.entity_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hex_color', full_name='calixa.domain.tag.Tag.hex_color', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=139,
)

_TAG.fields_by_name['entity_type'].enum_type = common__pb2._ENTITYTYPE
DESCRIPTOR.message_types_by_name['Tag'] = _TAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tag = _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), {
  'DESCRIPTOR' : _TAG,
  '__module__' : 'tag_pb2'
  # @@protoc_insertion_point(class_scope:calixa.domain.tag.Tag)
  })
_sym_db.RegisterMessage(Tag)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
