# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dreamai_obj',
                'doc_host': 'https://HamzaFarhan.github.io',
                'git_url': 'https://github.com/HamzaFarhan/dreamai_obj',
                'lib_path': 'dreamai_obj'},
  'syms': { 'dreamai_obj.core': { 'dreamai_obj.core.blur': ('core.html#blur', 'dreamai_obj/core.py'),
                                  'dreamai_obj.core.blur_faces_video': ('core.html#blur_faces_video', 'dreamai_obj/core.py'),
                                  'dreamai_obj.core.box_overlap': ('core.html#box_overlap', 'dreamai_obj/core.py'),
                                  'dreamai_obj.core.detect_obstacles_3': ('core.html#detect_obstacles_3', 'dreamai_obj/core.py'),
                                  'dreamai_obj.core.distance_to_camera': ('core.html#distance_to_camera', 'dreamai_obj/core.py'),
                                  'dreamai_obj.core.enumerate2': ('core.html#enumerate2', 'dreamai_obj/core.py'),
                                  'dreamai_obj.core.get_face_coords': ('core.html#get_face_coords', 'dreamai_obj/core.py'),
                                  'dreamai_obj.core.obj_detect': ('core.html#obj_detect', 'dreamai_obj/core.py'),
                                  'dreamai_obj.core.obj_model': ('core.html#obj_model', 'dreamai_obj/core.py')},
            'dreamai_obj.imports': {}}}
