# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from freem_protocols.furgame_league_protogen import control_pb2 as freem__protocols_dot_furgame__league__protogen_dot_control__pb2


class ControlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListGuilds = channel.unary_unary(
                '/furgame_league_protogen.control.ControlService/ListGuilds',
                request_serializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListGuildsRequest.SerializeToString,
                response_deserializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListGuildsResponse.FromString,
                )
        self.ListChannels = channel.unary_unary(
                '/furgame_league_protogen.control.ControlService/ListChannels',
                request_serializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListChannelsRequest.SerializeToString,
                response_deserializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListChannelsResponse.FromString,
                )
        self.ListVoices = channel.unary_unary(
                '/furgame_league_protogen.control.ControlService/ListVoices',
                request_serializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListVoicesRequest.SerializeToString,
                response_deserializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListVoicesResponse.FromString,
                )
        self.ListMembers = channel.unary_unary(
                '/furgame_league_protogen.control.ControlService/ListMembers',
                request_serializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListMembersRequest.SerializeToString,
                response_deserializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListMembersResponse.FromString,
                )
        self.SayInChannel = channel.unary_unary(
                '/furgame_league_protogen.control.ControlService/SayInChannel',
                request_serializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.SayInChannelRequest.SerializeToString,
                response_deserializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.SayInChannelResponse.FromString,
                )


class ControlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListGuilds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChannels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayInChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListGuilds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGuilds,
                    request_deserializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListGuildsRequest.FromString,
                    response_serializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListGuildsResponse.SerializeToString,
            ),
            'ListChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChannels,
                    request_deserializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListChannelsRequest.FromString,
                    response_serializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListChannelsResponse.SerializeToString,
            ),
            'ListVoices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVoices,
                    request_deserializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListVoicesRequest.FromString,
                    response_serializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListVoicesResponse.SerializeToString,
            ),
            'ListMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMembers,
                    request_deserializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListMembersRequest.FromString,
                    response_serializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListMembersResponse.SerializeToString,
            ),
            'SayInChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.SayInChannel,
                    request_deserializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.SayInChannelRequest.FromString,
                    response_serializer=freem__protocols_dot_furgame__league__protogen_dot_control__pb2.SayInChannelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'furgame_league_protogen.control.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ControlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListGuilds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/furgame_league_protogen.control.ControlService/ListGuilds',
            freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListGuildsRequest.SerializeToString,
            freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListGuildsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/furgame_league_protogen.control.ControlService/ListChannels',
            freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListChannelsRequest.SerializeToString,
            freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListChannelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListVoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/furgame_league_protogen.control.ControlService/ListVoices',
            freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListVoicesRequest.SerializeToString,
            freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListVoicesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/furgame_league_protogen.control.ControlService/ListMembers',
            freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListMembersRequest.SerializeToString,
            freem__protocols_dot_furgame__league__protogen_dot_control__pb2.ListMembersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayInChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/furgame_league_protogen.control.ControlService/SayInChannel',
            freem__protocols_dot_furgame__league__protogen_dot_control__pb2.SayInChannelRequest.SerializeToString,
            freem__protocols_dot_furgame__league__protogen_dot_control__pb2.SayInChannelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
