
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-01T14:38:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b85a1724e3f35f489db8230fa1c645cdc096f8b4",
 "version": "0.9.96"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
