# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import inbox_pb2 as inbox__pb2


class InboxServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateInboxItem = channel.unary_unary(
                '/calixa.domain.inbox.InboxService/CreateInboxItem',
                request_serializer=inbox__pb2.InboxItem.SerializeToString,
                response_deserializer=inbox__pb2.InboxItem.FromString,
                )
        self.PutInboxItem = channel.unary_unary(
                '/calixa.domain.inbox.InboxService/PutInboxItem',
                request_serializer=inbox__pb2.InboxItem.SerializeToString,
                response_deserializer=inbox__pb2.InboxItem.FromString,
                )
        self.GetInboxSummaryByPages = channel.unary_unary(
                '/calixa.domain.inbox.InboxService/GetInboxSummaryByPages',
                request_serializer=inbox__pb2.GetInboxSummaryRequest.SerializeToString,
                response_deserializer=inbox__pb2.GetInboxSummaryResponse.FromString,
                )
        self.GetInboxItemsForEntity = channel.unary_stream(
                '/calixa.domain.inbox.InboxService/GetInboxItemsForEntity',
                request_serializer=inbox__pb2.GetInboxItemsRequest.SerializeToString,
                response_deserializer=inbox__pb2.GetInboxItemsResponse.FromString,
                )


class InboxServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateInboxItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutInboxItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInboxSummaryByPages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInboxItemsForEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateInboxItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInboxItem,
                    request_deserializer=inbox__pb2.InboxItem.FromString,
                    response_serializer=inbox__pb2.InboxItem.SerializeToString,
            ),
            'PutInboxItem': grpc.unary_unary_rpc_method_handler(
                    servicer.PutInboxItem,
                    request_deserializer=inbox__pb2.InboxItem.FromString,
                    response_serializer=inbox__pb2.InboxItem.SerializeToString,
            ),
            'GetInboxSummaryByPages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInboxSummaryByPages,
                    request_deserializer=inbox__pb2.GetInboxSummaryRequest.FromString,
                    response_serializer=inbox__pb2.GetInboxSummaryResponse.SerializeToString,
            ),
            'GetInboxItemsForEntity': grpc.unary_stream_rpc_method_handler(
                    servicer.GetInboxItemsForEntity,
                    request_deserializer=inbox__pb2.GetInboxItemsRequest.FromString,
                    response_serializer=inbox__pb2.GetInboxItemsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calixa.domain.inbox.InboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InboxService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateInboxItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calixa.domain.inbox.InboxService/CreateInboxItem',
            inbox__pb2.InboxItem.SerializeToString,
            inbox__pb2.InboxItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutInboxItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calixa.domain.inbox.InboxService/PutInboxItem',
            inbox__pb2.InboxItem.SerializeToString,
            inbox__pb2.InboxItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInboxSummaryByPages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calixa.domain.inbox.InboxService/GetInboxSummaryByPages',
            inbox__pb2.GetInboxSummaryRequest.SerializeToString,
            inbox__pb2.GetInboxSummaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInboxItemsForEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/calixa.domain.inbox.InboxService/GetInboxItemsForEntity',
            inbox__pb2.GetInboxItemsRequest.SerializeToString,
            inbox__pb2.GetInboxItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
