
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-28T10:26:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd7415b6e9ee8319d9bba88a20aec209afaac1cf",
 "version": "0.9.95"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
